Added information about viable/strict lag to the nightly page
pytorch/test-infra pull request #4017
Opened 2023-04-12 12:53 UTC by DanilBaibak

Added information about viable/strict lag to the nightly page.

2023-04-13 16:17 UTC, ZainRizvi requested changes
What's the motivation for adding this data?

Comparing the pages for pytorch/pytorch's nightly and master pages, they show the exact same value for v/s lag, which is probably expected since it's v/s lag is the time delay between the repo's v/s and master branches.

By any chance can you get all the information you need from the hud.pytorch.org/metrics page? Or were you wanting this information for other domain repos?

2023-04-13 16:17 UTC, ZainRizvi commented on torchci/pages/hud/[repoOwner]/[repoName]/[branch]/[[...page]].tsx
> +  const viableStrictLag = data === undefined || data.length === 0 ? undefined : `viable/strict lag: ${data[0]["strict_lag_sec"]}h`;
The units are off here:

```suggestion
  const viableStrictLag = data === undefined || data.length === 0 ? undefined : `viable/strict lag: ${data[0]["strict_lag_sec"]} sec`;
```

Though I'd suggest actually changing the units to be the most course possible ("X hours, Y minutes) to make it easier understand.

Our metrics page uses the format "X.Yh", which is also okay

2023-04-14 12:28 UTC, DanilBaibak commented
Yes, the motivation is to add information about viable/strict lag to the nightly page exactly for the domains. But this already sounds like a small project :)

2023-05-08 20:10 UTC, ZainRizvi approved these changes

2023-05-08 20:10 UTC, ZainRizvi commented on torchci/pages/hud/[repoOwner]/[repoName]/[branch]/[[...page]].tsx
> +    const timeLagInHours = Math.floor(data[0]["strict_lag_sec"] / 3600);
How do you feel about making it a bit more granular by adding a decimal place?

```suggestion
    const timeLagInHours = (data[0]["strict_lag_sec"] / 3600).toFixed(1);
```

2024-05-31 09:56 UTC, closed without merging