Metrics
pytorch/test-infra pull request #4590
Opened 2023-09-26 00:03 UTC by clee2000

2023-10-06 15:00 UTC, ZainRizvi requested changes
As per offline convo, could you please split this PR up into two: One which adds the new heuristic data and one that adds all the other refactorings?

2023-10-13 20:44 UTC, clee2000 commented on torchci/scripts/utils.py
> +import rockset  # type: ignore[import]
i moved the functions out to their own files, but they seem a bit short haha

I also named it with utils in front for the files that are new

2023-10-13 20:45 UTC, clee2000 commented on torchci/scripts/utils.py
> +        return " N/A"
leftover from a time when i was relying on spacing instead of just using a csv

2023-10-13 20:46 UTC, clee2000 commented on torchci/scripts/td_heuristic_historical_edited_files.py
> +from collections import defaultdict
possibly a future thing, but also weird python module import problems make this annoying

2023-10-20 16:29 UTC, ZainRizvi approved these changes

2023-10-20 16:29 UTC, ZainRizvi commented on torchci/scripts/td_heuristic_historical_edited_files.py
> +        test_files = [x[5:-3] for x in changed_files if x[5:-3] in invoking_files]
What's special about this range of rows? Can you add a comment, or better yet replace these numbers with constants that help explain the significance of this range?  More specifically, why are the other rows excluded from this range?

2023-10-20 16:29 UTC, ZainRizvi commented on torchci/scripts/td_heuristic_profiling.py
> +    correlation_dict = get_profiling_dict()
should correlation_dict be renamed to profiling_dict?

2023-10-20 16:29 UTC, ZainRizvi commented on torchci/scripts/utils.py
> +def cache_json(func):
❤️

2023-10-20 16:29 UTC, ZainRizvi commented on torchci/scripts/utils.py
> +    # Requires that both input and output but json serializable.
```suggestion
    # Requires that both input and output be json serializable.
```

2023-10-23 20:34 UTC, merged