Forces docker login on calculate-docker-image for ECR
pytorch/test-infra pull request #4991
Opened 2024-03-08 14:14 UTC by jeanschmidt

2024-03-08 15:28 UTC, zxiiro approved these changes

2024-03-08 15:45 UTC, atalman requested changes

2024-03-08 15:45 UTC, atalman commented on .github/actions/calculate-docker-image/action.yml
>        id: check-image
What is the context here ? Could you please add some PR description.

There is an extra if statement in Build and push docker image  step like this, why do we want to skip it ? 
```
if: ${{ steps.calculate-image.outputs.skip != 'true' && (inputs.always-rebuild || steps.check-image.outputs.rebuild) }}
```

2024-03-08 16:21 UTC, atalman commented
if OIDC is required, please use these 2 steps: https://github.com/pytorch/test-infra/blob/atalman-test/.github/workflows/linux_gh_job.yml#L123

2024-03-08 17:57 UTC, atalman commented
@jeanschmidt this action is used in multiple core workflows:
```
.github/workflows/_android-build-test.yml:        uses: pytorch/test-infra/.github/actions/calculate-docker-image@main
.github/workflows/_android-full-build-test.yml:        uses: pytorch/test-infra/.github/actions/calculate-docker-image@main
.github/workflows/_bazel-build-test.yml:        uses: pytorch/test-infra/.github/actions/calculate-docker-image@main
.github/workflows/_docs.yml:        uses: pytorch/test-infra/.github/actions/calculate-docker-image@main
.github/workflows/_linux-build.yml:        uses: pytorch/test-infra/.github/actions/calculate-docker-image@main
.github/workflows/_linux-test.yml:        uses: pytorch/test-infra/.github/actions/calculate-docker-image@main
.github/workflows/_rocm-test.yml:        uses: pytorch/test-infra/.github/actions/calculate-docker-image@main
.github/workflows/_xpu-test.yml:        uses: pytorch/test-infra/.github/actions/calculate-docker-image@main
.github/workflows/docker-builds.yml:        uses: pytorch/test-infra/.github/actions/calculate-docker-image@main
.github/workflows/target-determination-indexer.yml:        uses: pytorch/test-infra/.github/actions/calculate-docker-image@main
```

Lets commit it to a separate branch and create a test PR  in pytorch/pytorch to test the changes.

2024-03-08 18:46 UTC, jeanschmidt commented
@atalman tests are being performed in https://github.com/pytorch/pytorch/pull/119544/files 

this is a critical workflow to enable ARC, so I will be following with the less beautiful solution with `docker login` and we can reiterate into figure out why AWS own actions are not working

2024-03-11 20:39 UTC, jeanschmidt commented
Relevant signals gathered by running the pull job on pytorch/pytorch

https://github.com/pytorch/pytorch/actions/runs/8237759663/job/22527270971

2024-03-12 07:09 UTC, DanilBaibak approved these changes

2024-03-12 14:46 UTC, jeanschmidt commented
Bypassing merge protections, given that signals are green and I believe we're in a good position to move forward.

2024-03-12 14:46 UTC, merged

2024-03-12 15:11 UTC, atalman commented
@pytorchmergebot revert -m "Broke lint jobs on trunk"

2024-03-12 15:11 UTC, atalman commented
@pytorchmergebot revert -m "Broke lint jobs on trunk" -c nosignal

2024-03-12 15:15 UTC, atalman commented
@jeanschmidt 
```
Unable to find image '308535385114.dkr.ecr.us-east-1.amazonaws.com/tool/alpine:latest' locally
docker: Error response from daemon: Head "https://308535385114.dkr.ecr.us-east-1.amazonaws.com/v2/tool/alpine/manifests/latest": no basic auth credentials.
See 'docker run --help'.
```

This is the error I am seeing:
https://github.com/pytorch/pytorch/actions/runs/8251057961/job/22567219192?pr=121728

2024-03-12 17:01 UTC, huydhn commented
I happen to have a PR https://github.com/pytorch/pytorch/pull/121691 to switch `308535385114.dkr.ecr.us-east-1.amazonaws.com/tool/alpine` to the upstream image https://hub.docker.com/_/alpine (cause why not) and it seems to work.  May be it would help resolve this error?

2024-03-12 20:02 UTC, atalman commented
I think @jeanschmidt added this change to support arc runner. If Arc can support [hub.docker.com/_/alpine](https://hub.docker.com/_/alpine) We probably should be good.

2024-03-12 20:56 UTC, huydhn commented
The clear benefit is that we don't need to sync images from docker hub to our ECR anymore.  This is a manual step that I don't think anyone would remember to do from time to time