Add decompress and base64 decode
pytorch/test-infra pull request #61
Opened 2021-07-15 05:15 UTC by zhouzhuojie

Due to the payload size limit of 6mb of lambda function invocation limit, this defaults to handle event that has a `compressed_logs` field now.

2021-07-15 16:11 UTC, janeyx99 approved these changes

2021-07-15 16:13 UTC, malfet requested changes
Can we make lambda a bit more flexible/resilient to errors?
I.e. something like `if 'base64_compressed_logs' in event and len(event)==1:`

2021-07-15 21:31 UTC, zhouzhuojie commented
> Can we make lambda a bit more flexible/resilient to errors?
> I.e. something like `if 'base64_compressed_logs' in event and len(event)==1:`

@malfet updated with the safety checks and tests

2021-07-15 21:53 UTC, driazati approved these changes

2021-07-15 22:30 UTC, malfet approved these changes

2021-07-15 22:33 UTC, merged

2023-05-17 23:28 UTC, clee2000 commented
These machines started queueing:
- linux.rocm.gpu, 4 machines, 0.25972222222222224 hours